### ISSUE TITLE
자료 수집 [2020-02-22마감, 23발송] 

### ISSUE THREAD

**Issue by godrm** [letswiftconf/newsletter#1]
여기에 02-23까지 보낼 자료를 수집해보겠습니다.

**Comment by godrm** [comment]
대수적으로 알아보는 타입 체계
https://pilgwon.github.io/post/episode-4-algebraic-data-types

**Comment by rollmind** [comment]
여기다 댓글을 달아보겠습니다

**Comment by rollmind** [comment]
영어도 될지 몰라 일단 링커 걸어 볼께요 안되면 번역 하겠습니다
SwiftUI에서 안전하게 뷰 상태 갱신하기
https://swiftui-lab.com/state-changes/

**Comment by godrm** [comment]
영어 자료보다는 한글 자료를 우선하는 게 좋을 것 같아요. 
그렇다고 안할 수는 없을텐데, 문서 아래 부분에 모아도 될 것 같구요. 
뭔가 카테고리 분류를 할 방법을 찾아보죠. 지금 생각나는 건 한글/영문, 블로그/강좌/컨퍼런스/동영상 등등 이런거요 
번역을 해주신다면 더 좋죠 ㅎㅎ

**Comment by rollmind** [comment]
넵 일단 한글 자료 위주로 시작 하겠습니다

**Comment by godrm** [comment]
이전 유용한 글을 되살리는 것도 좋은 생각 같아요. 매주 한 개라도 넣으면 좋겠네요. 
섹션을 구분해서 해보는 것도 좋겠네요. 
`새로운 소식`, `유물발굴`, `해외 소식`, `스폰서십`, `인터뷰` 다양한 걸 생각해보겠습니다.

**Comment by rollmind** [comment]
https://zeddios.tistory.com/m/957

**Comment by younatics** [comment]
야곰의 스위프트 프로그래밍
https://edu.goorm.io/learn/lecture/1141/야곰의-스위프트-프로그래밍/lesson/43304/시작-전-필독사항###

**Comment by godrm** [comment]
> 야곰의 스위프트 프로그래밍
> [https://edu.goorm.io/learn/lecture/1141/야곰의-스위프트-프로그래밍/lesson/43304/시작-전-필독사항###](https://edu.goorm.io/learn/lecture/1141/%EC%95%BC%EA%B3%B0%EC%9D%98-%EC%8A%A4%EC%9C%84%ED%94%84%ED%8A%B8-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D/lesson/43304/%EC%8B%9C%EC%9E%91-%EC%A0%84-%ED%95%84%EB%8F%85%EC%82%AC%ED%95%AD###)

아니 갑자기 예전 강좌를 추천하신 겁니까? ㅎㅎ

**Comment by Sa-ryong** [comment]
아래와 같은 형태는 어떨까요? 

-----------------------------------------------------

[새로운 소식] Alamofire 5.0.0 업데이트!
https://github.com/Alamofire/Alamofire/releases/tag/5.0.0

Alamofire의 메이저 버전 업데이트가 있었습니다. 애플이 추천하는 방향으로의 DispatchQueue 적용 등을 위해 코어를 재구현했다고 합니다. Decodable을 기본 지원하고, EventMonitor, RequestAdapter, RequestInterceptor 등 세부 과정을 제어하기 위한 인터페이스들이 추가되었습니다.
자세한 마이그레이션 가이드는 아래 링크에.. Result 처리가 Swift 5.0의 표준 타입을 사용하는 등 breaking change가 다소 있습니다.
https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%205.0%20Migration%20Guide.md

**Comment by godrm** [comment]
> 아래와 같은 형태는 어떨까요?
> 
> [새로운 소식] Alamofire 5.0.0 업데이트!
> https://github.com/Alamofire/Alamofire/releases/tag/5.0.0
> 

와우 좋네요!
역시 경험이 녹아있으시네요. 저도 링크, 요약이 함께 있으면 좋겠습니다.

**Comment by godrm** [comment]
이렇게 이슈에 추천하는 경우에 작성 방법도 readme에 써놔야 겠네요.

**Comment by godrm** [comment]
[블로그] 스위프트 5에서 ABI가 정해지고 나서 XCFramework 을 추천하고 있습니다. 
뭐가 좋아진걸까요? WWDC 2019에서 발표한 내용을 민소네님께서 번역해서 정리해주셨습니다. 

http://minsone.github.io/ios/mac/ios-wwdc-2019-binary-frameworks-in-swift-little-summary-and-translate

**Comment by Sa-ryong** [comment]
> [블로그] 스위프트 5에서 ABI가 정해지고 나서 XCFramework 을 추천하고 있습니다.
> 뭐가 좋아진걸까요? WWDC 2019에서 발표한 내용을 민소네님께서 번역해서 정리해주셨습니다.
> 
> http://minsone.github.io/ios/mac/ios-wwdc-2019-binary-frameworks-in-swift-little-summary-and-translate

오오 역시 민소네 님이시네요. 저도 XCFramework 쓰고 나서 인생이 편해졌는데.. 이렇게 심층적으로 분석해주실 줄이야.. @.@

**Comment by rollmind** [comment]
@godrm 제가 한 발 늦었네요. XCFramework...

**Comment by godrm** [comment]
[애플] Sign with Apple 앱스토어 심사지침 
4월부터 소셜 로그인을 하거나 다른 서비스로 로그인 하는 경우는 Sign with Apple을 강제한다고 했었는데 그 시점이 다가오고 있습니다. 
준비중인 기업들이 많을텐데, 디자인 가이드 상으로 꼭 Sign with Apple 버튼을 동일하게 만들어야 하는건 아니라고 하더군요. 신규 앱이 아니더라도 이제 과감하게 도입해야 하는 시점일까요?

https://developer.apple.com/kr/app-store/review/guidelines/#sign-in-with-apple

**Comment by godrm** [comment]
[애플] Swift Playground for Mac 
아이패드 전용 앱이던 Swift Playground 앱을 카탈리스트로 변환해서 맥용으로 출시했네요. 실행해보기 완전 동일한 버전인 것 같습니다.
심각한 버그가 있는데, 아이패드 앱도, 새로 나온 맥용 앱도 iCloud 옵션을 사용하면 새로운 플레이그라운드를 열지 못하고 크래시됩니다 🤯
사용하시려면 iCloud 에서 Swift Playground를 끄고 사용하세요.

https://apps.apple.com/kr/app/swift-playgrounds/id1496833156?mt=12

**Comment by rollmind** [comment]
[블로그] PropertyWrapper를 이용한 값처리
(약간 식상할 수도 있는 PropertyWrapper에 대한 글인데, 처음 접하는 개발자도 이해하기 쉽게 쓰여져 있다고 생각해 공유합니다.)
PropertyWrapper의 사용 방법과 사용례를 알려드립니다.

https://medium.com/harrythegreat/swift-properywrapper를-이용한-값처리-a8ef0d87e8e

**Comment by rollmind** [comment]
[블로그] Standard Library Preview Package 
아직 Swift 배포 버전에 포함되지는 않았지만, Swift Evolution을 통과한 기능을 미리 사용해 볼 수 있는 Swift Package에 대한 내용을 담고 있습니다.

https://zeddios.tistory.com/m/962

**Comment by Sa-ryong** [comment]
> [블로그] PropertyWrapper를 이용한 값처리
> (약간 식상할 수도 있는 PropertyWrapper에 대한 글인데, 처음 접하는 개발자도 이해하기 쉽게 쓰여져 있다고 생각해 공유합니다.)
> PropertyWrapper의 사용 방법과 사용례를 알려드립니다.
> 
> [https://medium.com/harrythegreat/swift-properywrapper를-이용한-값처리-a8ef0d87e8e](https://medium.com/harrythegreat/swift-properywrapper%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EA%B0%92%EC%B2%98%EB%A6%AC-a8ef0d87e8e)

글을 읽어봤는데.. 사용예..라기보다는 너무 단순한 개념 설명에서 끝나네요. 개인적으론 젊은 분이 너무 단순한 사고에 집착하지 않나 하는 우려가 들긴 합니다만..^^;
그래도 한글이니까 밀어줍시다.ㅎㅎ;;

**Comment by rollmind** [comment]
@Sa-ryong 뉴스레터가 활발해지면 이런 저런 숨통이 많이 트이길 기대하고 있어요 ㅎㅎ

**Comment by rollmind** [comment]
@Sa-ryong 아 이거 오늘 아침에 다시 읽어봤는데 고민이 ... ㅋㅋㅋ

> > [블로그] PropertyWrapper를 이용한 값처리
> > (약간 식상할 수도 있는 PropertyWrapper에 대한 글인데, 처음 접하는 개발자도 이해하기 쉽게 쓰여져 있다고 생각해 공유합니다.)
> > PropertyWrapper의 사용 방법과 사용례를 알려드립니다.
> > [https://medium.com/harrythegreat/swift-properywrapper를-이용한-값처리-a8ef0d87e8e](https://medium.com/harrythegreat/swift-properywrapper%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EA%B0%92%EC%B2%98%EB%A6%AC-a8ef0d87e8e)
> 
> 글을 읽어봤는데.. 사용예..라기보다는 너무 단순한 개념 설명에서 끝나네요. 개인적으론 젊은 분이 너무 단순한 사고에 집착하지 않나 하는 우려가 들긴 합니다만..^^;
> 그래도 한글이니까 밀어줍시다.ㅎㅎ;;

아 이거 오늘 아침에 다시 읽어봤는데, 넣는에 맞는지 고민이 되네요... @godrm @Sa-ryong 어떻세요? 필터링을 하는게 맞을까요. 이대로 넣어서 독자들의 좋은 교류가 있기를 기대하는게 맞을까요?

**Comment by godrm** [comment]
[해외] iOS 성능에 대한 숨겨진 팁들
전직 애플 개발자가 정리한 성능 개선을 위한 팁입니다. UILabel 조차 무겁다면 뭘 써야 할까요? 

https://www.fadel.io/blog/posts/ios-performance-tips-you-probably-didnt-know/

----

**Comment by godrm** [comment]
> 오늘 아침에 다시 읽어봤는데, 저도 넣는게 맞는지 고민이 들기 시작합니다. @godrm @Sa-ryong 어떻세요? 어느 정도 수준을 유지할 수 있도록 필터링을 하는게 맞을까요. 이대로 넣어서 독자들의 좋은 교류가 있기를 기대해야 할까요?

개인적인 의견은 iOS 한글 자료 자체가 많지 않아서 우선 시도해보는 건 좋을 것 같은데요, 
너무 흔하거나 일반적인 내용이라면 제외해도 될 것 같은 생각도 있습니다. 
뉴스레터 대상이 어떤 사람들일가요? 학생? 현업 개발자? 
1-2년차만 되도 관심없을 것 같은 주제는 걸러야 하나. 
역시 고객을 고민해보게 되네요 ㅎㅎ

**Comment by hyukhur** [comment]
* 해외 자료는 간단하게 tl;dr 처럼 간단한 결론만 논하고 넘어가는 것은 어떨까요? 
* 깊은 주제부터 얕은 주제로 나열하면 독자들이 fast exit 처럼 빠르게 훓고 넘길 수 있지 않을까요?
협업 개발자라면 새소식 위주로, 학생이라면 질 좋은 글을 찾을 것 같아요.
* Oldest but goodies 처럼 일년전 뉴스들 중에 의미
있는 것들을 하나씩 풀어봐도 좋을 것 같아요. 가끔 놓치고 넘어가는 경우도 겪어서...

**Comment by Sa-ryong** [comment]
> > 오늘 아침에 다시 읽어봤는데, 저도 넣는게 맞는지 고민이 들기 시작합니다. @godrm @Sa-ryong 어떻세요? 어느 정도 수준을 유지할 수 있도록 필터링을 하는게 맞을까요. 이대로 넣어서 독자들의 좋은 교류가 있기를 기대해야 할까요?
> 
> 개인적인 의견은 iOS 한글 자료 자체가 많지 않아서 우선 시도해보는 건 좋을 것 같은데요,
> 너무 흔하거나 일반적인 내용이라면 제외해도 될 것 같은 생각도 있습니다.
> 뉴스레터 대상이 어떤 사람들일가요? 학생? 현업 개발자?
> 1-2년차만 되도 관심없을 것 같은 주제는 걸러야 하나.
> 역시 고객을 고민해보게 되네요 ㅎㅎ

@godrm @rollmind 저도 공감입니다. 한글이라면, 내용 상 오류가 없는 한은 넣어주는 게 맞을 것 같습니다. 대신 카테고리를 [Beginner] 로 분류해서 공유하면 어떨까 싶네요. ㅎㅎ

**Comment by Sa-ryong** [comment]
> [해외] iOS 성능에 대한 숨겨진 팁들
> 전직 애플 개발자가 정리한 성능 개선을 위한 팁입니다. UILabel 조차 무겁다면 뭘 써야 할까요?
> 
> https://www.fadel.io/blog/posts/ios-performance-tips-you-probably-didnt-know/
> 
> 해외 자료는 어떤 주제를 얼마나 넣어야 할까도 고민입니다.

ㅎㅎ.. 코드 깎는 노인.. 그 경우라면 물론 그냥 직접 draw하는 걸로 해결을..ㅎㅎ
근데 iOS는 안드로이드에 비해 메모리 관리 효율이 굉장히 좋아서 UILabel의 비트맵 데이터로 인해 메모리 사용이 곤란해 질 일은 없을 것 같은데.. 엄청난 길이의 문장을 표시하는 경우는 물론 다르겠지만요.ㅎㅎ
보통 UILabel의 비트맵 처리로 곤란한 경우는 퍼포먼스보다는 품질 이슈가 더.. 예를 들면 글자 사이즈를 확대하는 애니메이션 같은 경우, 생각없이 구현하면 문자 품질이 형편없이 나오니까요.

**Comment by rollmind** [comment]
> > [해외] iOS 성능에 대한 숨겨진 팁들
> > 전직 애플 개발자가 정리한 성능 개선을 위한 팁입니다. UILabel 조차 무겁다면 뭘 써야 할까요?
> > https://www.fadel.io/blog/posts/ios-performance-tips-you-probably-didnt-know/
> > 해외 자료는 어떤 주제를 얼마나 넣어야 할까도 고민입니다.
> 
> ㅎㅎ.. 코드 깎는 노인.. 그 경우라면 물론 그냥 직접 draw하는 걸로 해결을..ㅎㅎ
> 근데 iOS는 안드로이드에 비해 메모리 관리 효율이 굉장히 좋아서 UILabel의 비트맵 데이터로 인해 메모리 사용이 곤란해 질 일은 없을 것 같은데.. 엄청난 길이의 문장을 표시하는 경우는 물론 다르겠지만요.ㅎㅎ
> 보통 UILabel의 비트맵 처리로 곤란한 경우는 퍼포먼스보다는 품질 이슈가 더.. 예를 들면 글자 사이즈를 확대하는 애니메이션 같은 경우, 생각없이 구현하면 문자 품질이 형편없이 나오니까요. 저도 처음엔 당연히 벡터 드로잉일거라고 생각해서, 품질이 이상하게 나오는 걸 보고 당황했는데 내부를 알고 나서 현타왔었던 기억이 나네요..ㅎㅎ;;

pdf image asset - preserve vector data 설정에 대한 내용이 동일하겠네요. 요즘 알고 당황 ㅎㅎ

**Comment by godrm** [comment]
그래도 UILabel 성능이 좋아진 편입니다. 예전에는 내부에서 WebView 로직이 렌더링해서 그리는 형식이었는데 Core Text 가 생기면서 직접 그리고 있으니까요 ㅎㅎ 
성능도 상대적이라 CALayer 와 Core Animation도 무겁다는 회사도 있었습니다 :)

**Comment by godrm** [comment]
> * 해외 자료는 간단하게 tl;dr 처럼 간단한 결론만 논하고 넘어가는 것은 어떨까요?
> * 깊은 주제부터 얕은 주제로 나열하면 독자들이 fast exit 처럼 빠르게 훓고 넘길 수 있지 않을까요?
>   협업 개발자라면 새소식 위주로, 학생이라면 질 좋은 글을 찾을 것 같아요.
> * Oldest but goodies 처럼 일년전 뉴스들 중에 의미
>   있는 것들을 하나씩 풀어봐도 좋을 것 같아요. 가끔 놓치고 넘어가는 경우도 겪어서...

early exit 이라니 guard 문법을 써야 하나 고민했네요 ㅋㅋ
모든 케이스를 만족시켜야 하는건지 생각해본거였죠. 해보면서 차츰 설문도 하고 그래서 맞춰봐도 될 것 같아요. 
우선은 다양하고 쉬운 것부터 어려운 것까지 모아둘 수만 있어도 의미가 있는 것 같거든요.

**Comment by godrm** [comment]
여기까지 내용을 정리해서 push했습니다. 
https://github.com/letswiftconf/newsletter/blob/master/issue%231.md

구글 Gsuite로 메일 전용 계정도 만들었고, 도메인 설정도 완료했습니다.
메일링 서비스도 기본 설정을 완료했습니다.
메일 템플릿을 확인해보고 시범으로 메일을 보내보겠습니다. 확인해주세요 :)

**Comment by Sa-ryong** [comment]
[Beginner] WWDC 세션 비디오, 무엇부터 어떻게 볼까?
https://sungdoo.dev/retrospective-or-psa/wwdc-watch-guide/
WWDC에 개발자들이 고민하는 문제의 답이 이미 상당히 제시되어 있는 걸 모르는 분들이 많던데.. 영어 압박 때문인지..

깊이 있는 내용은 아니지만 공유의 가치는 있을 것 같군요.^^

**Comment by Sa-ryong** [comment]
으악 간발의 차이..ㅎㅎㅎ;;;

**Comment by godrm** [comment]
> [Beginner] WWDC 세션 비디오, 무엇부터 어떻게 볼까?
> https://sungdoo.dev/retrospective-or-psa/wwdc-watch-guide/
> WWDC에 개발자들이 고민하는 문제의 답이 이미 상당히 제시되어 있는 걸 모르는 분들이 많던데.. 영어 압박 때문인지..
> 
> 깊이 있는 내용은 아니지만 공유의 가치는 있을 것 같군요.^^

마지막에 올려주신 것도 추가해볼게요 ㅎㅎ

**Comment by godrm** [comment]
첫 뉴스레터를 성공적으로 발송했습니다. 다음 이슈에서 만나요 👏🏻
