### ISSUE TITLE
제2호 (2020-03-08 발송 예정)

### ISSUE THREAD

**Issue by godrm** [letswiftconf/newsletter#2]
제1호처럼 여기에 자료를 분류하고 수집해서 정리하면 될 것 같습니다.

**Comment by godrm** [comment]
제1호 발행이후 하루만 지났지만, 의미있는 데이터라서 공유합니다. 
가입자는 +100명 정도 늘었고, 오픈율 57%, 클릭율 22.9%
me.com, iCloud.com, mac.com 주소로 전송 실패한 경우가 있어서 문의했습니다. 

<img width="1057" alt="Screen Shot 2020-02-24 at 5 25 59 PM" src="https://user-images.githubusercontent.com/278988/75137416-e591c500-572a-11ea-8314-f20da917676e.png">
<img width="1024" alt="Screen Shot 2020-02-24 at 5 26 41 PM" src="https://user-images.githubusercontent.com/278988/75137424-ea567900-572a-11ea-89d8-90fcc1f6b070.png">

위에서 보는 것처럼 국내 자료보다 해외 자료 클릭율이 높은 것 같은 느낌입니다. 
차츰 어떤 취향(?)이 있는지 볼 수 있을 것 같습니다.

**Comment by Sa-ryong** [comment]
올라온 이슈들 메일로 깔끔하게 정리하고, 분석까지..ㅎㅎ

흥미로운 결과이군요. 이제까지 운영해온 결과와도 비숫한 것 같습니다.
아무래도 비슷한 주제라면 한글 정보 쪽이 압도적으로 클릭이 높은 경향이 있긴 합니다만, 언어보다는 제목 자체가 더 영향을 많이 주는 것 같습니다. 이번에도 해외 자료는 워낙에 매력적인(?) 제목인데 비해, 한글 자료들은 초보적인 것이거나, 반대로 민소네 님과 필권 님의 글은 상당히 가치가 높은 글이긴 하지만 극소수의 개발자들만 실제로 관심이 있을 내용이라..ㅎㅎ

**Comment by godrm** [comment]
그래서 다양한 이야기를 전달하는 것이 좋을 것 같습니다. 커뮤니티 저변이 넓어진 반면에 생산하는 콘텐츠는 저변이 너무 빈약합니다. 
저도 2주에 하나라도 글 하나는 써보려고 노력중입니다 ㅎㅎ 잘 될지 모르겠네요

**Comment by godrm** [comment]
[스위프트 포럼] https://forums.swift.org/t/swift-soars-ever-higher/34036
드디어 윈도우에서 스위프트 하위 Foundation을 빌드할 수 있게 되었다는 소식입니다. 
정확히는 리눅스 테스트 케이스가 1714개 인데, 1706를 통과했다고 하네요. 아직 UNIX 계열 API 문제가 남아있다고 합니다. 
정작 리눅스 계열도 macOS와 다르게 안되는게 남아있는데, 그래도 꽤나 진전이 되었네요.
Visual Studio 에서 직접 스위프트를 컴파일할 수 있는 날이 곧 오나봅니다. 

[해외 블로그] https://kean.github.io/post/swiftui-data-flow
SwiftUI에서 데이터 흐름 관점으로 설명하는 글입니다. 
선언적인 뷰를 만들고 @Published, @ObservedObject, @Binding, @State, @Environment 활용해서 데이터가 어떻게 전달되는지 설명해줍니다. 

[기타 - 해외] https://llvm.discourse.group/t/mlir-news-1st-edition-2-21-2020/544
LLVM 하위 그룹에 머신러닝 관련 처리를 위한 MLIR 관련 뉴스레터가 시작됐네요. 

[국내 블로그] https://brunch.co.kr/@jamess/27
애플 앱스토어의 이상한 반려 사유들에 대한 경험담을 정리해주셨습니다.

**Comment by godrm** [comment]
[도구] https://gist.github.com/dsabanin/e1fe9bdc03d429d6cbcc7be13add9e6d
Xcode 에서 Internal Debug 메뉴를 활성화하는 방법이라고 합니다. 
우리에게 이런 메뉴가 정말 필요할까요? 힘내라 Xcode개발팀

**Comment by godrm** [comment]
[디자인] 디자이너가 정리한 iOS UI 디자인 용어
https://link.medium.com/IemomVQcq4

iOS개발자 여러분, 디자이너가 물어보면 이렇게 알려주면 되나봅니다.

**Comment by godrm** [comment]
[디자인] 디자이너가 정리한 iOS UI 디자인 용어
https://link.medium.com/IemomVQcq4

iOS개발자 여러분, 디자이너가 물어보면 이렇게 알려주면 되나봅니다.

**Comment by godrm** [comment]
[도구] Xcode 빌드 설정 값에 대한 설명을 모아놓은 사이트
https://xcodebuildsettings.com

이걸 보니 예전에 제가 Xcode 책에 정리했던 내용이 있던 것 같은데, 바뀐 부분도 있으니 자료를 다시 살려봐야겠네요.

**Comment by Sa-ryong** [comment]
> [국내 블로그] https://brunch.co.kr/@jamess/27
> 애플 앱스토어의 이상한 반려 사유들에 대한 경험담을 정리해주셨습니다
제가 아는 거랑 다른 게 조금 있네요.
1.의 경우는 심사요청시에 테스트용 아이디, 비밀번호를 등록하면 회원가입이 어려워도 통과되는 걸로 알고 있습니다. 최근에도 초대제 회원 앱이나, 은행지점애서만 가입이 가능한 앱을 만든 적이 있습니다.
7.은 아직은 경고일뿐인데.. 당장 RxSwift가 UIWebview를 포함하고 있는데, 저 논라면 상당수 앱들이 업로드불가..ㅎㅎ

**Comment by godrm** [comment]
[오픈소스] 아이콘팩토리에서 만든 마크다운 지원하는 AttributedString 
https://github.com/chockenberry/MarkdownAttributedString

마크다운을 표시하려고 할 때 마땅한게 없었던 분들께 도움이 될 것 같아요.

**Comment by godrm** [comment]
> > [국내 블로그] https://brunch.co.kr/@jamess/27
> > 애플 앱스토어의 이상한 반려 사유들에 대한 경험담을 정리해주셨습니다
> 
> 제가 아는 거랑 다른 게 조금 있네요.
> 1.의 경우는 심사요청시에 테스트용 아이디, 비밀번호를 등록하면 회원가입이 어려워도 통과되는 걸로 알고 있습니다. 최근에도 초대제 회원 앱이나, 은행지점애서만 가입이 가능한 앱을 만든 적이 있습니다.
> 7.은 아직은 경고일뿐인데.. 당장 RxSwift가 UIWebview를 포함하고 있는데, 저 논리라면 상당수 앱들이 업로드불가..ㅎㅎ;;

약간 꼼수네요. 최근에는 엔터프라이즈 계정 어뷰징 사례가 많아서, 엔터프라이즈 계정 신청이 어려워졌습니다. 특정 기업이나 그룹만 사용하는 앱인 경우는 business.apple.com 을 통해서 배포하도록 권장하고 있습니다. 
자세하게 안 읽어봤는데, 애매한 게 좀 있네요. 꼼꼼하게 읽어보고 빼던가 해야겠어요 ㅜㅜ

**Comment by Sa-ryong** [comment]
> 약간 꼼수네요. 최근에는 엔터프라이즈 계정 어뷰징 사례가 많아서, 엔터프라이즈 계정 신청이 어려워졌습니다. 특정 기업이나 그룹만 사용하는 앱인 경우는 business.apple.com 을 통해서 배포하도록 권장하고 있습니다.

아 그런 건 몰랐군요. 저희 회사도, 저희 고객사도 큰 회사들이라 보통 애플 직원이 와서 친절히(?) 설정 다해줘서 쉬운 건지 알았...;;;

**Comment by godrm** [comment]
[디자인] 디자이너 한 명에게 영감을 받아서 시작된 뉴모피즘(Neumorphism)은 새로운 UI 트랜드가 될 수 있을까?
https://brunch.co.kr/@cliche-cliche/32

iOS 7부터 바뀌어버린 UI 디자인을 언제쯤 바꿀까요? iOS 13에서 다크모드가 들어갔었으니까 iOS 14에서 테마를 지원해준다거나 그러지는 않겠죠? ㅎㅎ

**Comment by godrm** [comment]
[블로그] Codable 과 NSCoding 프로토콜의 차이점 
https://medium.com/@codesquad_yoda/codable-vs-nscoding-%EC%B0%A8%EC%9D%B4%EC%A0%90-4b47e240c0b8?sk=9b2b0eb22f5e1e18d695bf53e115e246

오랜만에 직접 블로그를 작성해봤습니다. 상속 관계가 있어 다형성 동작이 필요한 클래스를 인코딩/디코딩했을 때 Codable에서는 다이나믹 타입 정보가 포함되지 않아 다형성이 동작하지 않는 경우를 설명합니다. 
이런 경우는 NSCoding과 NSKeyedArchiver 조합을 사용해야만 합니다.

**Comment by Sa-ryong** [comment]
오오 훌륭~+_+
근데 결론 1에 오타가..^^;;
“Codable 프로토콜은 NSCoding 프로토콜은 대체제가 아니다.”

**Comment by Sa-ryong** [comment]
영어지만 재미있는 내용이라 공유해봅니다.

[기타-해외] iOS 개발자 설문조사
https://iosdevsurvey.com/2019/
iOS 개발자 설문조사 중 최대 규모(2,290명)인 The iOS Developer Community Survey에서 결과를 발표했습니다. 주목할만한 내용을 꼽아보자면,
-평균적인 iOS 개발자는 상용 앱 개발에서 8:2 정도의 비율로 Swift:Objective-C를 섞어 쓰고 있으며, 42%가 모든 코드를 Swift로 짜고 있다고 합니다.
-Swift 언어에 대한 평균 만족도는 8.3점(10점 만점)이었으며, 69.9%가 성숙기에 접어들었다고 평가했고, 14.1%만이 써드파티 라이브러리가 Objective C와의 호환성을 유지해야한다는데 동의했습니다.
-65%의 응답자가 최근 1년 이내에 개인 앱을 앱스토어 올린 경험이 있다고 합니다. 그중 44%는 무료 앱이었다고 하고, 14.4%가 1년에 1,000 달러 이상 수익을 올린다고 합니다.
-AR기술 기반 비즈니스의 현황과 전망을 묻는 문항에 대한 평균 점수는 각각 3.3, 3.1으로 다소 비관적이었지만, AR 기술에 대한 자체에 대한 관심은 4.6점으로 조금 더 높았습니다.

**Comment by Sa-ryong** [comment]
[기타-해외] 2020년판 iOS 개발자 면접 질문
https://ordinarycoding.com/articles/ios-developer-interview-questions-2020/
개발 면접에서 나올 수 있는 67개의 질문을 정리했습니다. 항상 기술적 호기심을 유지하고 있는 중급 정도의 개발자라면 어렵지 않게 대답할 수 있을 질문들이 많아 보입니다. 다만, 경험 많은 면접관이라면 단편적인 지식을 묻는 게 아니라, 이런 질문들을 화두로, 기술의 장단점/특징에 대한 분석, 왜 그런 개념이 생겼는지 이유, 무엇보다 그것의 내부가 어떻게 구현되어 있는지 등 심층적으로 파고들기 때문에, 일하다가 흔히 겪는 기술적 이슈에 대해서 항상 깊이 있게 연구하는 자세가 필요하다고 생각합니다.

**Comment by godrm** [comment]
[오픈소스] Baraba(바라봐) https://github.com/nsoojin/baraba

ARKit 혹은 AVFoundation을 써서 사용자 얼굴을 트래킹해서 아이폰을 바라보고 있을때 화면의 스크롤뷰(테이블뷰, 컬렉션뷰 등등)를 자동으로 스크롤해주는 라이브러리입니다.

사용자가 컨텐츠 소비를 위해 스크롤을 많이 해야하는 앱을 만들기 위해서,
코드 단 3줄이면 쉽게 적용해볼 수 있다고 합니다!

**Comment by Sa-ryong** [comment]
[디자인-해외] 그림으로 설명하는 Apple iOS 13 디자인 가이드라인
https://learnui.design/blog/ios-design-guidelines-templates.html
애플 HIG(Human Interface Guideline)은 UI구현을 위해 반드시 숙지하고 있어야 할 내용이지만, 글이 너무 길어서 영미인조차도 읽기 어려워하는 문서입니다. 이를 그림으로 알기 쉽게 설명하는 가이드라인 해설 문서가 최근 업데이트 되었습니다.

**Comment by Sa-ryong** [comment]
[기타] iOS 개발자 싱가폴 이직기
https://soojin.ro/blog/singapore
자꾸 개발자들 싱숭생숭 해지게 이런 거 공유해도 되는지 모르겠습니다만..^^; 정말 재밌고 유익하게 봤습니다. ^^b

**Comment by rollmind** [comment]
공유하고싶은 글들을 이미 다 올려주셨군요. 더 열심히 찾고 + 생산을 해야겠습니당.

**Comment by rollmind** [comment]
> [도구] https://gist.github.com/dsabanin/e1fe9bdc03d429d6cbcc7be13add9e6d
> Xcode 에서 Internal Debug 메뉴를 활성화하는 방법이라고 합니다.
> 우리에게 이런 메뉴가 정말 필요할까요? 힘내라 Xcode개발팀

와 재밌는 팁이네요. 활성화 해보고 가지고 놀아보겠습니다.

<img width="173" alt="스크린샷 2020-03-04 오전 10 09 14" src="https://user-images.githubusercontent.com/3011832/75834753-4d699f00-5e00-11ea-8977-d7fc6bcf5003.png">

**Comment by godrm** [comment]
> [기타] iOS 개발자 싱가폴 이직기
> https://soojin.ro/blog/singapore
> 자꾸 개발자들 싱숭생숭 해지게 이런 거 공유해도 되는지 모르겠습니다만..^^; 정말 재밌고 유익하게 봤습니다. ^^b
> 여담이지만 저도 한국에서 면접관일 때 이직사유를 꼭 물어봤었는데, 외국 나와서 많이 후회했습니다. 면접관의 감춰진 의도는 1.(더 나은 처우가 이직의 큰 이유인 줄 뻔히 알지만) 그래도 진취적이고 긍정적인 사유를 대는가, 2. (현직장에 만족하고 있으면 이직할 리도 없지만) 현직장에 대해 나쁘게만 얘기하지 않고 불만사항 개선을 위해서 어느 정도의 노력은 했는가를 듣고 싶어서인데.. 그러지말고 과거의 여러 경험들에 대해 structural question을 던지는 게 훨씬 의미있는 정보를 얻을 수 있는데, 얼마나 어리석은 질문만 했는지..:(

이거 위에 오픈소스 만든 노수진님 글이라 같이 소개할까 싶습니다. 혼자있어서 심심한지 자꾸 올리네요 ㅋㅋㅋ 
얼른 싱가폴로 놀러가고 싶네요.

**Comment by rollmind** [comment]
> > [기타] iOS 개발자 싱가폴 이직기
> > https://soojin.ro/blog/singapore
> > 자꾸 개발자들 싱숭생숭 해지게 이런 거 공유해도 되는지 모르겠습니다만..^^; 정말 재밌고 유익하게 봤습니다. ^^b
> > 여담이지만 저도 한국에서 면접관일 때 이직사유를 꼭 물어봤었는데, 외국 나와서 많이 후회했습니다. 면접관의 감춰진 의도는 1.(더 나은 처우가 이직의 큰 이유인 줄 뻔히 알지만) 그래도 진취적이고 긍정적인 사유를 대는가, 2. (현직장에 만족하고 있으면 이직할 리도 없지만) 현직장에 대해 나쁘게만 얘기하지 않고 불만사항 개선을 위해서 어느 정도의 노력은 했는가를 듣고 싶어서인데.. 그러지말고 과거의 여러 경험들에 대해 structural question을 던지는 게 훨씬 의미있는 정보를 얻을 수 있는데, 얼마나 어리석은 질문만 했는지..:(
> 
> 이거 위에 오픈소스 만든 노수진님 글이라 같이 소개할까 싶습니다. 혼자있어서 심심한지 자꾸 올리네요 ㅋㅋㅋ
> 얼른 싱가폴로 놀러가고 싶네요.

심심하시면 Cocoa Internals 2편 Swift Internals 어떻신가요? 헤헤

**Comment by rollmind** [comment]
> [기타] iOS 개발자 싱가폴 이직기
> https://soojin.ro/blog/singapore
> 자꾸 개발자들 싱숭생숭 해지게 이런 거 공유해도 되는지 모르겠습니다만..^^; 정말 재밌고 유익하게 봤습니다. ^^b
> 여담이지만 저도 한국에서 면접관일 때 이직사유를 꼭 물어봤었는데, 외국 나와서 많이 후회했습니다. 면접관의 감춰진 의도는 1.(더 나은 처우가 이직의 큰 이유인 줄 뻔히 알지만) 그래도 진취적이고 긍정적인 사유를 대는가, 2. (현직장에 만족하고 있으면 이직할 리도 없지만) 현직장에 대해 나쁘게만 얘기하지 않고 불만사항 개선을 위해서 어느 정도의 노력은 했는가를 듣고 싶어서인데.. 그러지말고 과거의 여러 경험들에 대해 structural question을 던지는 게 훨씬 의미있는 정보를 얻을 수 있는데, 얼마나 어리석은 질문만 했는지..:(



> [디자인-해외] 그림으로 설명하는 Apple iOS 13 디자인 가이드라인
> https://learnui.design/blog/ios-design-guidelines-templates.html
> 애플 HIG(Human Interface Guideline)은 UI구현을 위해 반드시 숙지하고 있어야 할 내용이지만, 글이 너무 길어서 영미인조차도 읽기 어려워하는 문서입니다. 이를 그림으로 알기 쉽게 설명하는 가이드라인 해설 문서가 최근 업데이트 되었습니다.

이건 번역해서 올려도 좋겠네용. 오늘 번역해봐야겠어요.

**Comment by godrm** [comment]
제가 아니라 저 블로그 주인장이 심심해 하더라구요 ㅋㅋㅋ 
저는 안 심심해요.. 응(?)

**Comment by rollmind** [comment]
[SPM] 웹 어셈블리가 스위프트 패키지 매니저의 플랫폼에 추가될 거 같습니다.
이걸 보고나서야 알았는데, WebAssembly support for the Swift(https://swiftwasm.org) 라는 프로젝트가 활발하네요.
리뷰 대기중이며 컨트리뷰터가 익숙하다 했더니 2019 try! Swift Tokyo 2019에 swift metatype에 대한 발표를 하셨던 분이시군요. (참조 https://kateinoigakukun.hatenablog.com/entry/2019/03/22/184356) 

https://github.com/apple/swift-package-manager/pull/2640

**Comment by godrm** [comment]
제이펍에서 핵심만 골라 배우는 SwiftUI 기반 iOS 프로그래밍 책을 출간했습니다. 다들 관심이 많은데 이제 SwiftUI 저변이 넓어질 수 있을까요? 
https://jpub.tistory.com/m/1018
샘플 미리보기 https://jpub.tistory.com/attachment/cfile2.uf@99D45B4D5E6092D2039764.pdf

**Comment by godrm** [comment]
[오픈소스] https://github.com/davedelong/time
시간을 다스리는 닥터스트레인지가 되고 싶은 개발자(?)가 Time 이라는 스위프트 패키지로 배포하는 오픈소스를 시작했습니다. 기존 Date/Time 보다 더 직관적인 스위프트 프레임워크를 만드는 게 목표라고 합니다.

**Comment by godrm** [comment]
[해외 블로그] 애플에서 main argument 파싱을 도와주는 오픈 소스 저장소를 공개했습니다. https://github.com/apple/swift-argument-parser

```
import ArgumentParser

struct Repeat: ParsableCommand {
    @Flag(help: "Include a counter with each repetition.")
    var includeCounter: Bool

    @Option(name: .shortAndLong, help: "The number of times to repeat 'phrase'.")
    var count: Int?

    @Argument(help: "The phrase to repeat.")
    var phrase: String

    // continued below…
}
```

사용 예제를 재빠르게 설명한 블로그 자료가 올라왔습니다. https://www.avanderlee.com/swift/command-line-tool-package-manager

**Comment by godrm** [comment]
> [SPM] 웹 어셈블리가 스위프트 패키지 매니저의 플랫폼에 추가될 거 같습니다.
> [apple/swift-package-manager#2640](https://github.com/apple/swift-package-manager/pull/2640)
> 
> 이걸 보고나서야 알았는데, WebAssembly support for the Swift(https://swiftwasm.org) 라는 프로젝트가 활발하네요.
> 리뷰 대기중이며 컨트리뷰터가 익숙하다 했더니 2019 try! Swift Tokyo 2019에 swift metatype에 대한 발표를 하셨던 분이시군요. (참조 https://kateinoigakukun.hatenablog.com/entry/2019/03/22/184356)

이 발표 재밌었는데... wasm 내용을 스위프트에서 어떻게 활용할 수 있는 걸까요?

**Comment by godrm** [comment]
[해외 - 기타] git-flow의 창시가 며칠전 git-flow를 만들고 되돌아보는 문장을 글 맨 앞에 추가했습니다. 
https://nvie.com/posts/a-successful-git-branching-model/

역시 모든 것을 만족할 수 있는 방법은 없나 봅니다. 유명하다고 무조건 받아들여서 사용해야 하는 건 아니니까요.

>  If your team is doing continuous delivery of software, I would suggest to adopt a much simpler workflow (like GitHub flow) instead of trying to shoehorn git-flow into your team.

> To conclude, always remember that panaceas don't exist. Consider your own context. Don't be hating. Decide for yourself.

**Comment by godrm** [comment]
[국내 블로그 by wayne] 테스트를 좀 더 잘하고 싶을 때 Moya
https://mildwhale.github.io/2020-03-07-getting-started-with-moya/

**Comment by godrm** [comment]
발송 완료했습니다. https://stib.ee/um12
